### ISSUE TITLE
Update the bioRxiv link to our Nature Comm. publication

### ISSUE THREAD

**Issue by ArtemSokolov** [labsyspharm/driad-website#1]
Update https://github.com/labsyspharm/driad-website/blob/d3a3477ca871e0266d85ce6679ed74bcf809291c/R/ui.R#L61-L64

to point to https://www.nature.com/articles/s41467-021-21330-0 instead.

**Comment by clemenshug** [comment]
Thanks Artem! I finally updated the reference.
